# List of configuration priority:
# - VM options
# - application.properties
# - application.yaml
server:
  port: 8080 # default

spring:
  main:
    web-application-type: servlet # default

  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: postgres
