services:
  database:
    container_name: pfsd_postgres
    image: postgres:alpine
    environment:
      POSTGRES_DB: 'postgres' # Default: taken from POSTGRES_USER environment variable
      POSTGRES_USER: 'postgres' # Default: `postgres`
      POSTGRES_PASSWORD: 'postgres'
      # Allows setting custom path for storing Postgres container data.
      PGDATA: /var/lib/postgresql/data # Default: `/var/lib/postgresql/data`
    # Setting hostname allows for simpler connection with pgAdmin.
    hostname: pfsd_postgres_hostname
    ports:
      - '5432:5432'
    networks:
      - pfsd_network
    volumes:
      - pfsd_postgres_volume:/var/lib/postgresql/data
    restart: on-failure

  database_console:
    container_name: pfsd_pgadmin
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: pgadmin@localhost.dev
      PGADMIN_DEFAULT_PASSWORD: pgadmin
      # Run as single user mode.
      PGADMIN_CONFIG_SERVER_MODE: 'False' # Default `True`
    hostname: pfsd_pgadmin_hostname
    ports:
      - '5050:80'
    networks:
      - pfsd_network
    volumes:
      - pfsd_pgadmin_volume:/var/lib/pgadmin # Default: `/var/lib/pgadmin`
    depends_on:
      - database
    restart: on-failure

networks:
  pfsd_network:
    driver: bridge

# Named volumes.
volumes:
  pfsd_postgres_volume:
  pfsd_pgadmin_volume:
